### ISSUE TITLE
react-script 5.0.0 issue for use-contractkit

### ISSUE THREAD

**Issue by davilink92** [celo-org/use-contractkit#152]
Hello everyone,
I implemented use-contrackit on a react project, but i have some error in several libraries. 

For example, i encurred in this error: "Module not found: Error: Can’t resolve ‘crypto’" or Browser etc. 

Someone resolved it without use react-app-rewired or similar? 

I found that is a problem with react script 5.0.0 that use a new version of webpack. 

I would like to resolve without having to downgrade.

Thank you, 

regards

**Comment by nicolasbrugneaux** [comment]
Hi @davilink92 do you still have the issue?

**Comment by davilink92** [comment]
> Hi @davilink92 do you still have the issue?

Yes, i have it with react-script 5.0.0, so i did dowgrade react-script 5.0.0 to 4.0.3. :(

**Comment by nicolasbrugneaux** [comment]
Finally had the time to investigate this and reproduce it locally. While this is a real bug, we can't really do anything about it at the moment, this is on Facebook's side when they upgraded CRA to use webpack 5. You can see their team discussing the issue here: https://github.com/facebook/create-react-app/issues/11756 

From here you have different choices. You can stick to CRA 4.x as you did. You can use CRACO (https://github.com/gsoft-inc/craco) to include manually the polyfills. Or simply wait for CRA's team to merge the fix and release it (they have a PR close to being merged here https://github.com/facebook/create-react-app/pull/11764 that does just that.)

I understand this can be frustrating. As a side note, you can use react 18 with CRA 4.x with no problems AFAIK, so maybe that's worth a try?

**Comment by paulayo93** [comment]
> Finally had the time to investigate this and reproduce it locally. While this is a real bug, we can't really do anything about it at the moment, this is on Facebook's side when they upgraded CRA to use webpack 5. You can see their team discussing the issue here: [facebook/create-react-app#11756](https://github.com/facebook/create-react-app/issues/11756)
> 
> From here you have different choices. You can stick to CRA 4.x as you did. You can use CRACO (https://github.com/gsoft-inc/craco) to include manually the polyfills. Or simply wait for CRA's team to merge the fix and release it (they have a PR close to being merged here [facebook/create-react-app#11764](https://github.com/facebook/create-react-app/pull/11764) that does just that.)
> 
> I understand this can be frustrating. As a side note, you can use react 18 with CRA 4.x with no problems AFAIK, so maybe that's worth a try?

please I need help with this @nicolasbrugneaux
