### ISSUE TITLE
imToken 

### ISSUE THREAD

**Issue by patricknbaron** [celo-org/use-contractkit#67]
When connected via imToken wallet, the provider shows as 'MetaMask' 

![IMG_A6CEB1DED6B3-1](https://user-images.githubusercontent.com/45248974/142037050-d8f39b1b-d92b-479f-9542-e9144cb905ab.jpeg)

**Comment by aslawson** [comment]
@patricknbaron @dckesler did we add imToken as a wallet option? I'm assuming this is through the user clicking the generic "WalletConnect" option. We'll be pulling the wallet details from the central WalletConnect repo and limiting to those that specify they work with the Celo network Id, so that repo should have the wallet config details.

**Comment by patricknbaron** [comment]
Ubeswap added it as an option. Please try app.moola.market on your mobile device to see what I'm talking about: https://github.com/Ubeswap/use-contractkit/blob/master/packages/use-contractkit/src/connectors/connectors.ts

**Comment by dckesler** [comment]
So this was on Ubeswap's fork of use-contractkit so I can't speak specifically to this issue. However, we did add something to not show "MetaMask" unless we're sure that's what it is. Otherwise it will have a generic message of "Injected"
